### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by pachisi456** [pachisi456/clocktrol#2]
```
E/flutter ( 4615): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter ( 4615): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:512:7)
E/flutter ( 4615): #2      _parseJson (dart:convert-patch/convert_patch.dart:32:10)
E/flutter ( 4615): #3      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter ( 4615): #4      JsonCodec.decode (dart:convert/json.dart:153:41)
E/flutter ( 4615): #5      jsonDecode (dart:convert/json.dart:96:10)
E/flutter ( 4615): #6      Clockify.getTodaysHours (package:clocktrol/clockify.dart:24:21)
E/flutter ( 4615): <asynchronous suspension>
E/flutter ( 4615): #7      Workday.fetchClockify (package:clocktrol/workday.dart:48:34)
E/flutter ( 4615): #8      new Workday.<anonymous closure> (package:clocktrol/workday.dart:17:57)
E/flutter ( 4615): #9      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 4615): #10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 4615): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 4615): #12     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1024:26)
E/flutter ( 4615): #13     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 4615): #14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 4615): #15     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1008:26)
E/flutter ( 4615): #16     _Closure.call (dart:core-patch/function.dart)
E/flutter ( 4615): #17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 4615): #18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 4615): #19     _Closure.call (dart:core-patch/function.dart)
E/flutter ( 4615): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 4615): 

```

**Comment by pachisi456** [comment]
Seems outdated/fixed.
